language: node_js
node_js:
- lts/*

after_success:
  - npm run coverage

deploy:
  provider: npm
  email: dasrick@gmail.com
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
    repo: Regis24GmbH/aws-lambda-nodejs-response
